/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Waterstation;

import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author Jander
 */
public class LoginFrame1 extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame1() throws IOException {
    
        setSize(1200, 700);
   
        initComponents();
    
              ScaledImages();
    }
public void ScaledImages() throws IOException{
    
    /*BufferedImage image = ImageIO.read(getClass().getResource(""));
BufferedImage smoothImage = new BufferedImage(image.getWidth(), image.getHeight(), BufferedImage.TYPE_INT_ARGB);
Graphics2D g2d = smoothImage.createGraphics();

// Enable anti-aliasing
g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

// Draw the image on to the graphics object
g2d.drawImage(image, 0, 0, null);
g2d.dispose();*/

// Now you can use smoothImage where you need the smoothed version of the image

     
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Right = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        FBicon = new javax.swing.JLabel();
        YTicon = new javax.swing.JLabel();
        websiteicon = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Left = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LoginUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LoginPass = new javax.swing.JPasswordField();
        SignUp_LoginPage = new javax.swing.JButton();
        LoginButton = new javax.swing.JButton();
        label1 = new java.awt.Label();
        showpass1 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Water Station Log In");
        setFocusable(false);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 243, 243));
        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 700));
        jPanel2.setLayout(null);

        Right.setBackground(new java.awt.Color(0, 159, 249));
        Right.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Water Station (1).png"))); // NOI18N
        jLabel4.setText("jLabel6");

        FBicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/facebook.png"))); // NOI18N
        FBicon.setText("jLabel6");
        FBicon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FBicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FBiconMouseClicked(evt);
            }
        });

        YTicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/youtube.png"))); // NOI18N
        YTicon.setText("jLabel7");
        YTicon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        YTicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                YTiconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                YTiconMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                YTiconMousePressed(evt);
            }
        });

        websiteicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/save-water.png"))); // NOI18N
        websiteicon.setText("jLabel8");
        websiteicon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        websiteicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                websiteiconMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Business Links::");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("@WaterStationReal");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("@WaterStationReal");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("WaterStationDotCom");

        javax.swing.GroupLayout RightLayout = new javax.swing.GroupLayout(Right);
        Right.setLayout(RightLayout);
        RightLayout.setHorizontalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RightLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RightLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(RightLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(FBicon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(YTicon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(websiteicon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RightLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel10)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)))))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        RightLayout.setVerticalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(15, 15, 15)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FBicon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YTicon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(websiteicon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jPanel2.add(Right);
        Right.setBounds(0, 0, 600, 700);

        Left.setBackground(new java.awt.Color(233, 225, 225));
        Left.setForeground(new java.awt.Color(205, 245, 253));
        Left.setMinimumSize(new java.awt.Dimension(400, 500));

        jLabel1.setBackground(new java.awt.Color(0, 159, 249));
        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 159, 249));
        jLabel1.setText("Login to Inventory System");

        LoginUser.setBackground(new java.awt.Color(255, 234, 234));
        LoginUser.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        LoginUser.setBorder(null);
        LoginUser.setCaretColor(new java.awt.Color(153, 153, 153));
        LoginUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LoginUser.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        LoginUser.setSelectionColor(new java.awt.Color(255, 234, 234));
        LoginUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginUserActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 159, 249));
        jLabel2.setText("Password:");

        jLabel3.setBackground(new java.awt.Color(0, 51, 51));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 159, 249));
        jLabel3.setText("Username:");

        LoginPass.setBackground(new java.awt.Color(255, 234, 234));
        LoginPass.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        LoginPass.setBorder(null);
        LoginPass.setEchoChar('•');
        LoginPass.setSelectionColor(new java.awt.Color(255, 234, 234));
        LoginPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginPassActionPerformed(evt);
            }
        });

        SignUp_LoginPage.setBackground(new java.awt.Color(0, 159, 249));
        SignUp_LoginPage.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        SignUp_LoginPage.setForeground(new java.awt.Color(255, 255, 255));
        SignUp_LoginPage.setText("SIGN UP");
        SignUp_LoginPage.setAlignmentY(0.0F);
        SignUp_LoginPage.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        SignUp_LoginPage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignUp_LoginPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_LoginPageActionPerformed(evt);
            }
        });

        LoginButton.setBackground(new java.awt.Color(0, 159, 249));
        LoginButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("LOGIN");
        LoginButton.setAlignmentY(0.0F);
        LoginButton.setAutoscrolls(true);
        LoginButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        LoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        label1.setForeground(new java.awt.Color(0, 159, 249));
        label1.setText("Need Account?");

        showpass1.setBackground(new java.awt.Color(233, 225, 225));
        showpass1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        showpass1.setForeground(new java.awt.Color(0, 159, 249));
        showpass1.setText("Show Password");
        showpass1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showpass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpass1ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/user (3).png"))); // NOI18N
        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
        Left.setLayout(LeftLayout);
        LeftLayout.setHorizontalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftLayout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftLayout.createSequentialGroup()
                        .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(showpass1)
                            .addGroup(LeftLayout.createSequentialGroup()
                                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LoginPass, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LoginUser, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SignUp_LoginPage, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112))
        );
        LeftLayout.setVerticalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(showpass1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SignUp_LoginPage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jPanel2.add(Left);
        Left.setBounds(590, 0, 610, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void showpass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpass1ActionPerformed
        // TODO add your handling code here:

        if(showpass1.isSelected()){
            LoginPass.setEchoChar((char)0);
        }
        else{
            LoginPass.setEchoChar(('•'));
        }
    }//GEN-LAST:event_showpass1ActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
       
        //Identifying the user
         try {
            //database emtry
            
            Connection con2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/waterbizdb","root","filbert123");
            //accept user entry
            String user_name =  LoginUser.getText().trim();
            String user_pass = LoginPass.getText().trim();
            
          if(user_name.equals("")&&user_pass.equals("")){
            JOptionPane.showMessageDialog(null, "Please fill up Username and Password!");
            return;
        }
        else if(user_name.equals("")){
            JOptionPane.showMessageDialog(null, "Please fill up Username!");
            return;
        }
        else if(user_pass.equals("")){
            JOptionPane.showMessageDialog(null, "Please fill up Password!");
            return;
        }
            
            Statement stm = con2.createStatement();
            //select table
            String sql = "select * from account_signup where username='"+user_name+"'and password='"+user_pass+"'";
            ResultSet rs = stm.executeQuery(sql);
            
            if(rs.next()){
           JOptionPane.showMessageDialog(this, "Login Successful!");
                dispose();
                MainTable inventory = new MainTable();
                inventory.setVisible(true);
                
            }
            
       
            else{
                JOptionPane.showMessageDialog(this, "Username or Password is wrong. Try Again.");
                
                LoginUser.setText("");
                LoginPass.setText("");
                return;
            }
            con2.close();
            


        } catch (Exception ex) {
            Logger.getLogger(LoginFrame1.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_LoginButtonActionPerformed

    private void SignUp_LoginPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_LoginPageActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        try {
            new RegisterFrame().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(LoginFrame1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SignUp_LoginPageActionPerformed

    private void LoginPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginPassActionPerformed

    private void LoginUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginUserActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_LoginUserActionPerformed

    private void FBiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FBiconMouseClicked
        // TODO add your handling code here:
         try {
         
        Desktop.getDesktop().browse(new URI("https://www.facebook.com/RickAstley"));
         
    } catch (IOException | URISyntaxException e1) {
        e1.printStackTrace();
    }
    }//GEN-LAST:event_FBiconMouseClicked

    private void YTiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YTiconMouseClicked
        // TODO add your handling code here:
         try {
         
        Desktop.getDesktop().browse(new URI("https://www.youtube.com/watch?v=dQw4w9WgXcQ"));
         
    } catch (IOException | URISyntaxException e1) {
        e1.printStackTrace();
    }
    }//GEN-LAST:event_YTiconMouseClicked

    private void websiteiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_websiteiconMouseClicked
        // TODO add your handling code here:
              try {
         
        Desktop.getDesktop().browse(new URI("https://www.rickastley.co.uk"));
         
    } catch (IOException | URISyntaxException e1) {
        e1.printStackTrace();
    }
    }//GEN-LAST:event_websiteiconMouseClicked

    private void YTiconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YTiconMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_YTiconMousePressed

    private void YTiconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YTiconMouseEntered
        // TODO add your handling code here:
        
        
      
        
    }//GEN-LAST:event_YTiconMouseEntered


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("CrossPlatformLookAndFeel".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        System.setProperty("sun.java2d.uiScale", "1.5");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new LoginFrame1().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(LoginFrame1.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FBicon;
    private javax.swing.JPanel Left;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPasswordField LoginPass;
    private javax.swing.JTextField LoginUser;
    private javax.swing.JPanel Right;
    private javax.swing.JButton SignUp_LoginPage;
    private javax.swing.JLabel YTicon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label label1;
    private javax.swing.JCheckBox showpass1;
    private javax.swing.JLabel websiteicon;
    // End of variables declaration//GEN-END:variables
}
