/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication6;

/**
 *
 * @author Jander
 */
import com.toedter.calendar.JDateChooser;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Random;
import javax.swing.JComboBox;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
public class MainTable extends javax.swing.JFrame {

    /**
     * Creates new form MainTable
     */
    //jframe nameA
    public MainTable() {
        initComponents();
        showtable();
               Date currentDate = new Date();
        jDateChooser2.setMinSelectableDate(currentDate);
        // Get the selected date
    

        
    }

    
    
    public class UID {
    private int uniqueID;

    public UID() {
        Random random = new Random();
        this.uniqueID = random.nextInt(90000000) + 10000000; // This will generate a random integer between 10000000 and 99999999
}
    public int getUniqueID() {
        return this.uniqueID;
}
    }
    
    public void showtable() {
 
        
       try {
    Connection con3 = DriverManager.getConnection("jdbc:mysql://localhost:3306/waterbizdb","root","database1234567");
    PreparedStatement prstmnt = con3.prepareStatement("select * from waterstation");
    ResultSet rs1 = prstmnt.executeQuery();
    ResultSetMetaData rsmd1 = rs1.getMetaData();
    int n = rsmd1.getColumnCount();

    DefaultTableModel dtm = (DefaultTableModel) Station_Table.getModel();
    dtm.setRowCount(0);

    while (rs1.next()) {
        Vector v = new Vector();

        // Add values for each column once per iteration
        v.add(rs1.getInt("ProductID"));
        v.add(rs1.getString("Customer"));
        v.add(rs1.getString("Item_Name"));
        v.add(rs1.getString("Container_Type"));
        v.add(rs1.getString("Quantity"));
        v.add(rs1.getString("Liters"));
        v.add(rs1.getString("Price"));
        v.add(rs1.getString("Date"));

        // Add the Vector to the DefaultTableModel
        dtm.addRow(v);
    }
} catch (SQLException sqle) {
    sqle.printStackTrace(); // Log the exception for debugging purposes
}
    
    
}
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conatinergroup = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Station_Table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        WaterType = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LitersOfWater = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        AmountSelect = new javax.swing.JTextField();
        Reset = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Bottle = new javax.swing.JRadioButton();
        Jug = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CustomerName = new javax.swing.JTextField();
        Amount = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ADDbutton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        Answer = new javax.swing.JLabel();
        Price_text1 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventory");
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(0, 159, 249));
        jPanel3.setPreferredSize(new java.awt.Dimension(1200, 700));

        jPanel2.setBackground(new java.awt.Color(238, 245, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 100));

        Station_Table.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Station_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Customer", "Item Name", "Container Type", "Quantity", "Liters", "Total Price", "Date"
            }
        ));
        Station_Table.setShowGrid(false);
        Station_Table.getTableHeader().setReorderingAllowed(false);
        Station_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Station_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Station_Table);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 159, 249));
        jLabel1.setText("ORDER INFORMATION");

        jButton2.setBackground(new java.awt.Color(0, 159, 249));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/bin.png"))); // NOI18N
        jButton2.setText("Delete");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 159, 249));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/support.png"))); // NOI18N
        jButton3.setText("Edit");
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );

        jPanel1.setBackground(new java.awt.Color(0, 159, 249));

        WaterType.setBackground(new java.awt.Color(255, 255, 255));
        WaterType.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        WaterType.setForeground(new java.awt.Color(0, 159, 249));
        WaterType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Purified", "Mineral water", "Alkaline water", " " }));
        WaterType.setBorder(null);
        WaterType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WaterTypeActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Customer's Order:");

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Water Type:");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Date:");

        LitersOfWater.setBackground(new java.awt.Color(255, 255, 255));
        LitersOfWater.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LitersOfWater.setForeground(new java.awt.Color(0, 159, 249));
        LitersOfWater.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "1 Liter", "6 Liters", "22 Liters" }));
        LitersOfWater.setBorder(null);
        LitersOfWater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LitersOfWaterActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Customer:");

        AmountSelect.setBackground(new java.awt.Color(255, 255, 255));
        AmountSelect.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AmountSelect.setForeground(new java.awt.Color(0, 159, 249));
        AmountSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AmountSelectMouseEntered(evt);
            }
        });
        AmountSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmountSelectActionPerformed(evt);
            }
        });
        AmountSelect.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AmountSelectKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AmountSelectKeyTyped(evt);
            }
        });

        Reset.setBackground(new java.awt.Color(255, 255, 255));
        Reset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Reset.setForeground(new java.awt.Color(0, 159, 249));
        Reset.setText("Reset");
        Reset.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Liters:");

        Bottle.setBackground(new java.awt.Color(0, 159, 249));
        conatinergroup.add(Bottle);
        Bottle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Bottle.setForeground(new java.awt.Color(255, 255, 255));
        Bottle.setText("Bottle");
        Bottle.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                BottleItemStateChanged(evt);
            }
        });
        Bottle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottleActionPerformed(evt);
            }
        });

        Jug.setBackground(new java.awt.Color(0, 159, 249));
        conatinergroup.add(Jug);
        Jug.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Jug.setForeground(new java.awt.Color(255, 255, 255));
        Jug.setText("Jug");
        Jug.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JugItemStateChanged(evt);
            }
        });
        Jug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Container Type:");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/water-cycle_1.png"))); // NOI18N
        jLabel8.setText("jLabel8");

        CustomerName.setBackground(new java.awt.Color(255, 255, 255));
        CustomerName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CustomerName.setForeground(new java.awt.Color(0, 159, 249));
        CustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerNameActionPerformed(evt);
            }
        });

        Amount.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        Amount.setForeground(new java.awt.Color(255, 255, 255));
        Amount.setText("Amount:");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/image-table/calendar.png"))); // NOI18N
        jLabel9.setText("jLabel9");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/image-table/jug.png"))); // NOI18N
        jLabel10.setText("jLabel9");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/image-table/customer.png"))); // NOI18N
        jLabel11.setText("jLabel9");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/image-table/quantity.png"))); // NOI18N
        jLabel12.setText("jLabel9");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/image-table/glass-of-water.png"))); // NOI18N
        jLabel13.setText("jLabel9");

        ADDbutton1.setBackground(new java.awt.Color(255, 255, 255));
        ADDbutton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ADDbutton1.setForeground(new java.awt.Color(0, 159, 249));
        ADDbutton1.setText("Add");
        ADDbutton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ADDbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDbutton1ActionPerformed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/image-table/switch.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Answer.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        Answer.setForeground(new java.awt.Color(255, 255, 255));

        Price_text1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        Price_text1.setForeground(new java.awt.Color(255, 255, 255));
        Price_text1.setText("Price:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(169, 169, 169))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ADDbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(CustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(Jug, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Bottle, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(LitersOfWater, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(AmountSelect, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(WaterType, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(67, 67, 67)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel4)
                                                        .addGap(48, 48, 48)
                                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Price_text1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Answer, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WaterType, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bottle)
                    .addComponent(Jug))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Amount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LitersOfWater, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AmountSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ADDbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Price_text1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Answer, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        
        String cusname = CustomerName.getText();
        JDateChooser date = jDateChooser2;
        String Amount_ent = AmountSelect.getText();
    }//GEN-LAST:event_ResetActionPerformed

    private void AmountSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmountSelectActionPerformed
        // TODO add your handling code here:
     
        
        
    }//GEN-LAST:event_AmountSelectActionPerformed

    private void LitersOfWaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LitersOfWaterActionPerformed
        // TODO add your handling code here:
        
         try{
    String selected = (String)LitersOfWater.getSelectedItem();
   // int value = Integer.parseInt(text);
    int valueInLiters;

                // Add if-else conditions based on the selected item
                if (selected.equals("1 Liter")) {
                    valueInLiters = 10;
                      int amount_value = Integer.parseInt(AmountSelect.getText());
                      int result = valueInLiters*amount_value;
                    Answer.setText(String.valueOf(result + " "+"₱"));
                } else if (selected.equals("6 Liters")) {
                    valueInLiters = 25;
                     int amount_value = Integer.parseInt(AmountSelect.getText());
                      int result = valueInLiters*amount_value;
                      Answer.setText(String.valueOf(result + " "+"₱"));
                } else if (selected.equals("22 Liters")) {
                    valueInLiters = 40;
                    
                     int amount_value = Integer.parseInt(AmountSelect.getText());
                      int result = valueInLiters*amount_value;
                      Answer.setText(String.valueOf(result + " "+"₱"));
                } else {
                    // Handle "Select" or other invalid selections
                    throw new IllegalArgumentException("Invalid selection");
                }
 
    
 }catch(NumberFormatException e){
     
     
     
 }
        
        
        
        String selectedValue = LitersOfWater.getSelectedItem().toString();
    }//GEN-LAST:event_LitersOfWaterActionPerformed

    private void WaterTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WaterTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WaterTypeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void CustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerNameActionPerformed

    private void AmountSelectKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AmountSelectKeyTyped
        // TODO add your handling code here:
        char valuetyped = evt.getKeyChar();
        if(!Character.isDigit(valuetyped)){
            evt.consume();
        }
        

        
    }//GEN-LAST:event_AmountSelectKeyTyped

    private void BottleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottleActionPerformed
        // TODO add your handling code here:
          
        
    }//GEN-LAST:event_BottleActionPerformed

    private void JugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugActionPerformed
        // TODO add your handling code here:
        
         
    }//GEN-LAST:event_JugActionPerformed
   
    private void ADDbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDbutton1ActionPerformed
        // TODO add your handling code here:
        try{
            
     UID uidGenerator = new UID();
    int randomUID = uidGenerator.getUniqueID();
             String cusname = CustomerName.getText().trim();
             
            
           Connection con2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/waterbizdb","root","database1234567");
           String sql1 =  "INSERT INTO waterstation (ProductID, Customer, Item_Name, Container_Type, Quantity, Liters, Price, Date) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
           PreparedStatement stmnt = con2.prepareStatement(sql1);
           
            //wag icopy
           Statement st1 = con2.createStatement();
          // String query1 = "Select * from waterstation";
          // ResultSet rs = st1.executeQuery(query1);
           //ResultSetMetaData rsmd = rs.getMetaData();
          
           //int column = rsmd.getColumnCount();
          // String[] colName = new String[column];
           //for(int x = 0; x<column x++) //hanggang dito
          /* while (rs.next()) {
    int ID = rs.getInt(1);
    String cus = rs.getString(2);
    String item = rs.getString(3);
    String Container = rs.getString(4);
    String Quantity = rs.getString(5);
    String Liters = rs.getString(6);
    String price = rs.getString(7);
    String Date = rs.getString(8);}*/

    // Add the row with both string and integer values

           //uid
           stmnt.setInt(1, randomUID);
           //customer
           stmnt.setString(2, cusname);
           //watertype
           String water_item;
           water_item = WaterType.getSelectedItem().toString();
           stmnt.setString(3, water_item);
           //container
           if(Jug.isSelected()){
               
               String container2 = Jug.getText();
               stmnt.setString(4, container2);
           }
           else if(Bottle.isSelected()){
               
               String container2 = Bottle.getText();
               stmnt.setString(4, container2);
           }
           //quntity
           stmnt.setInt(5, Integer.parseInt(AmountSelect.getText().trim()));
           //Liters
          
            String Liters = LitersOfWater.getSelectedItem().toString();
           stmnt.setString(6, Liters);
           //price
           stmnt.setString(7, Answer.getText().trim());
              //Date
        
              
              
         Date selectedDate = jDateChooser2.getDate();

        // Format the selected date
        SimpleDateFormat dateFormat = new SimpleDateFormat("MM-dd-yyyy");
        String formattedDate = dateFormat.format(selectedDate);
           
           stmnt.setString(8, formattedDate);
           stmnt.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) Station_Table.getModel();
           model.setRowCount(0);
           showtable();
           
           JOptionPane.showMessageDialog(null, "added successfully!");
        }
        
        
        
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_ADDbutton1ActionPerformed

    private void Station_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Station_TableMouseClicked
        // TODO add your handling code here:
       /* int i = Station_Table.getSelectedRow();
        TableModel model1 = Station_Table.getModel();
        CustomerName.setText(model1.getValueAt(i, 2).toString());
        String container_Type = model1.getValueAt(i, 4).toString();
        if(container_Type.equals(ABORT));*/
   UID uidGenerator = new UID();
int randomUID = uidGenerator.getUniqueID();
int id = Integer.parseInt(Station_Table.getValueAt(Station_Table.getSelectedRow(), 0).toString());

try {
    Connection con4 = DriverManager.getConnection("jdbc:mysql://localhost:3306/waterbizdb", "root", "database1234567");
    Statement st2 = con4.createStatement();
    ResultSet resu = st2.executeQuery("Select * from waterstation where id=" + id);

    while (resu.next()) {
        randomUID = resu.getInt("ProductID");
        CustomerName.setText(resu.getString("Customer"));
        WaterType.setSelectedItem(resu.getString("Item_Name"));
     
      String containerType = resu.getString("Container_Type");
    if ("Jug".equals(containerType)) {
        Jug.setSelected(true);
    } else if ("Bottle".equals(containerType)) {
        Bottle.setSelected(true);
    }
        AmountSelect.setText(resu.getString("Quantity"));
        LitersOfWater.setSelectedItem(resu.getString("Liters"));
        Answer.setText(resu.getString("Price"));
        jDateChooser2.setDate(resu.getDate("Date"));
    }
} catch (SQLException sqle) {
    sqle.printStackTrace(); // Log the exception for debugging purposes
}

       
        
    }//GEN-LAST:event_Station_TableMouseClicked

    private void AmountSelectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AmountSelectMouseEntered
        // TODO add your handling code here:
                   
        
        
        
        
    }//GEN-LAST:event_AmountSelectMouseEntered

    private void AmountSelectKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AmountSelectKeyReleased
        // TODO add your handling code here:
        
         try{
    String selected = (String)LitersOfWater.getSelectedItem();
   // int value = Integer.parseInt(text);
    int valueInLiters;

                // Add if-else conditions based on the selected item
                if (selected.equals("1 Liter")) {
                    valueInLiters = 10;
                      int amount_value = Integer.parseInt(AmountSelect.getText());
                      int result = valueInLiters*amount_value;
                    Answer.setText(String.valueOf(result + " "+"₱"));
                } else if (selected.equals("6 Liters")) {
                    valueInLiters = 25;
                     int amount_value = Integer.parseInt(AmountSelect.getText());
                      int result = valueInLiters*amount_value;
                      Answer.setText(String.valueOf(result + " "+"₱"));
                } else if (selected.equals("22 Liters")) {
                    valueInLiters = 40;
                    
                     int amount_value = Integer.parseInt(AmountSelect.getText());
                      int result = valueInLiters*amount_value;
                      Answer.setText(String.valueOf(result + " "+"₱"));
                } else {
                    // Handle "Select" or other invalid selections
                    throw new IllegalArgumentException("Invalid selection");
                }
 
    
                
                
                
                
                
                
                
                
                
 }catch(NumberFormatException e){
     
 }
        
    }//GEN-LAST:event_AmountSelectKeyReleased

    private void BottleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_BottleItemStateChanged
        // TODO add your handling code here:
        
       if (Bottle.isSelected()) {
        // Disable Item 2
        LitersOfWater.setEnabled(true);
        if (containsItem1(LitersOfWater, "6 Liters")&&containsItem1(LitersOfWater, "22 Liters")) {
            LitersOfWater.removeItem("6 Liters");
            LitersOfWater.removeItem("22 Liters");
        }
       
    } else {
        // Enable Item 2
        LitersOfWater.setEnabled(true);
        if (!containsItem1(LitersOfWater, "6 Liters")&&!containsItem1(LitersOfWater, "22 Liters")) {
            LitersOfWater.insertItemAt("6 Liters",1);
             LitersOfWater.insertItemAt("22 Liters",2);
       
        }
    }
}

// Check if the item is already present in the JComboBox
private boolean containsItem1(JComboBox<?> comboBox, Object item) {
    for (int i = 0; i < comboBox.getItemCount(); i++) {
        if (comboBox.getItemAt(i).equals(item)) {
            return true;
        }
    }
    return false;
        
        
    }//GEN-LAST:event_BottleItemStateChanged

    private void JugItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JugItemStateChanged
        // TODO add your handling code here:
  if (Jug.isSelected()) {
        // Disable Item 2
        LitersOfWater.setEnabled(true);
        if (containsItem(LitersOfWater, "1 Liter")) {
            LitersOfWater.removeItem("1 Liter");
        }
    } else {
        // Enable Item 2
        LitersOfWater.setEnabled(true);
        if (!containsItem(LitersOfWater, "1 Liter")) {
            LitersOfWater.insertItemAt("1 Liter", 1);
       
        }
    }
}

// Check if the item is already present in the JComboBox
private boolean containsItem(JComboBox<?> comboBox, Object item) {
    for (int i = 0; i < comboBox.getItemCount(); i++) {
        if (comboBox.getItemAt(i).equals(item)) {
            return true;
        }
    }
    return false;
        
        
        
        
    }//GEN-LAST:event_JugItemStateChanged
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("CrossPlatformLookAndFeel".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADDbutton1;
    private javax.swing.JLabel Amount;
    private javax.swing.JTextField AmountSelect;
    private javax.swing.JLabel Answer;
    private javax.swing.JRadioButton Bottle;
    private javax.swing.JTextField CustomerName;
    private javax.swing.JRadioButton Jug;
    private javax.swing.JComboBox<String> LitersOfWater;
    private javax.swing.JLabel Price_text1;
    private javax.swing.JButton Reset;
    private javax.swing.JTable Station_Table;
    private javax.swing.JComboBox<String> WaterType;
    private javax.swing.ButtonGroup conatinergroup;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
